version: "3.8"

services:
  frontend:
    build:
      context: ./pdf_parser_frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - pdf_parser_pdf_parser_network

  backend:
    build:
      context: ./pdf_parser_backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - minio
    environment:
      MINIO_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    networks:
      - pdf_parser_pdf_parser_network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio_data:/data
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    networks:
      - pdf_parser_pdf_parser_network

volumes:
  minio_data:

networks:
  pdf_parser_pdf_parser_network:
    driver: bridge